services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ems_sql
    environment:
      SA_PASSWORD: "Santhosh@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - ems_network

  api:
    build:
      context: ./EMS
      dockerfile: EMS.API/Dockerfile
    container_name: ems_api
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    networks:
      - ems_network
  frontend:
    build:
      context: ./EMS/ems-ui
      dockerfile: Dockerfile
    container_name: ems_ui
    ports:
      - "4200:80"
    depends_on:
      - api
networks:
  ems_network:
